FROM golang:latest AS builder

WORKDIR /app

COPY ./go.mod .
COPY ./go.sum .


RUN go mod download

COPY ./aggregator aggregator

RUN go build -o bin/obu obu/main.go 

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/bin/obu .

EXPOSE 8080

CMD ["./bin/obu"]
